name: Documentation
description: Found an issue in the documentation? You can use this one!
labels: ['documentation']
body:
  - type: markdown
    attributes:
      value: |
        * For questions, ask in [Discussions](https://github.com/x4ty/good-1st-issue/discussions).
        * Check to make sure someone hasn't already opened a similar [issue](https://github.com/x4ty/good-1st-issue/issues).

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A brief description of the question or issue
    validations:
      required: true

  - type: textarea
    id: extrainfo
    attributes:
      label: Additional information
      description: Is there anything else we should know about this issue?
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: This project has a Code of Conduct that all participants are expected to understand and follow.
      options:
        - label: I have read and agree to the project's [Code of Conduct](CODE_OF_CONDUCT.md)
          required: true
