# Generated by Django 4.1.3 on 2022-11-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerUpdateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_update_time', models.DateTimeField(auto_now_add=True)),
                ('server_update_status', models.BooleanField(default=False)),
                ('server_update_error', models.TextField(default='')),
            ],
            options={
                'verbose_name': 'Server Update',
                'verbose_name_plural': 'Server Updates',
            },
        ),
    ]
