# Generated by Django 4.1.3 on 2022-11-28 06:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Good1stIssueLabelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Label',
                'verbose_name_plural': 'Labels',
            },
        ),
        migrations.CreateModel(
            name='Good1stIssueModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_url', models.URLField(unique=True)),
                ('issue_title', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('issue_author', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('tweet_text', models.TextField(blank=True, default='', null=True)),
                ('tweet_id', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('tweet_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('tweeted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issue_labels', models.ManyToManyField(related_name='issues', to='good_1st_issue.good1stissuelabelmodel')),
            ],
            options={
                'verbose_name': 'Issue',
                'verbose_name_plural': 'Issues',
            },
        ),
    ]
